### ISSUE TITLE
Clarification regarding LaneBlocker and LaserscanDetector.

### ISSUE THREAD

**Issue by suchetanrs** [open-rmf/rmf_obstacle#24]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Hey @Yadunund !
I had some clarifications regarding running the lane blocking feature. 

### Regarding obstacles header.
I see from the discussion that led to this PR https://github.com/open-rmf/rmf_internal_msgs/pull/65 that a header was added to the ```Obstacles.msg```.
However looking at the latest source code on the ```main``` branch, the header field is not populated in [this file](https://github.com/open-rmf/rmf_obstacle/blob/main/rmf_obstacle_detector_laserscan/src/LaserscanDetector.cpp) from line 382. Since there was no PR related to [this](https://github.com/open-rmf/rmf_obstacle/issues/9) issue discussion of populating the header fields. Should I raise one?

### Regarding LaneBlocker Node
The lane blocker successfully sent the request to block lanes and I got messages on the topic as well. The logs of the lane blocker node is available on this [gist](https://gist.github.com/suchetanrs/f6f52aa9208a1e6c12be09a088387653)
The issue was in the fleet adapter. It showed the following when the lanes callback was called. 
```
[fleet_adapter-16]     fleet_handle.open_lanes(msg.open_lanes)                                                                                                 
[fleet_adapter-16] AttributeError: 'rmf_adapter.EasyFullControl' object has no attribute 'open_lanes'                                                          
```
I have uploaded a more complete log on this [gist](https://gist.github.com/suchetanrs/51891f8358f31c1b2f2af6153e2fb5af)
Can you please let me know what steps I need to take to fix this? 

Regards,
Suchetan

**Comment by Yadunund** [comment]
Thanks for the ticket! It looks like we need to update the implementation to populate the header. I'm hoping the plugin system proposed in #22 will alleviate the need for each obstacle detector to ensure these things. The plugins can just implement a method to set a new list of obstacles along with a header. The node which loads the plugins will be responsible for populating the message that will be published.

Regading the fleet adapter issue, I do see the `opne_lanes` API available in the [python bindings](https://github.com/open-rmf/rmf_ros2/blob/67f69db94e08e88dcad7ecf34faa260078e0317b/rmf_fleet_adapter_python/src/adapter.cpp#L392-L393). It might be worth opening a ticket in `rmf_demos` while also including more details of your setup.

**Comment by suchetanrs** [comment]
Hi @Yadunund,
Thanks a lot for your response! I have raised a [PR](https://github.com/open-rmf/rmf_obstacle/pull/25) regarding the header issue. Like you mentioned, populating this is not desired since the final message would be a set of all obstacles published by all the sensors / plugins. However, to ensure working of this package until this is done, I created the PR.

Turns out that the issue in which open_lanes and close_lanes functions were not being found was a simple fix. I have detailed this in [this](https://github.com/open-rmf/rmf_demos/issues/221) ticket and also raised [this](https://github.com/open-rmf/rmf_demos/pull/220) PR for the same. 
I am closing this issue since my query was resolved. Thanks a lot for your help! :D

**Comment by Yadunund** [comment]
Awesome, thanks for the fix!
